apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lu-diverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jimmy0006/lu-diverse-frontend:sha-92d9503
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
