apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: upload-size
  namespace: lu-diverse
spec:
  buffering:
    maxRequestBodyBytes: 1153433600  # 1100MB
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ludiverse-ingress
  namespace: lu-diverse
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: lu-diverse-upload-size@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: ludiverse.jimmy-home.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
